name: CI

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Download artifacts
      uses: actions/upload-artifact@v4
      with:
         name: my-artifact
         path: requirements.txt

    - name: Install dependencies
      run: |
        pip install -r .github/workflows/requirements.txt
